_BASE_: "../Base-MGN.yml"

MODEL:
  BACKBONE:
    WITH_IBN: False
    EXTRA_BN: True
  PIXEL_MEAN: [89.896, 79.200, 80.073]
  PIXEL_STD: [63.872, 64.305, 63.839]
INPUT:
  REA:
    MEAN: [0.0, 0.0, 0.0]
  DO_AUTOAUG: False
SOLVER:
  HEADS_LR_FACTOR: 1.0
  BACKBONE_BN_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 30
  IMS_PER_BATCH: 32

DATASETS:
  NAMES: ("CostumDataset",)
  TESTS: ("CostumDataset",)
  KWARGS: 'data_name:duke+split_mode:id+split_ratio:1.0'
  #ROOT: "C:/Users/danie/PycharmProjects/ComputerVision/DemoFastReId/fast-reid/datasets/our_Market-1501-v15.09.15"
  ROOT: "/../reid/market1501"
  #ROOT: "/home/dengpanfu/data"

TEST:
  EVAL_PERIOD: 60
  ROC_ENABLED: True

OUTPUT_DIR: "logs/CostumDataset/mgn_unsup"